version: '3.8'

services:
  app:
    build: ./app
    container_name: flask_app
    expose:
      - 5000

  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
